/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as LearnRoadmapIdRouteImport } from './routes/learn.$roadmapId'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'
import { Route as LearnRoadmapIdTopicIdRouteImport } from './routes/learn.$roadmapId_.$topicId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HabitsRoute,
} as any)
const LearnRoadmapIdRoute = LearnRoadmapIdRouteImport.update({
  id: '/$roadmapId',
  path: '/$roadmapId',
  getParentRoute: () => LearnRoute,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => HabitsRoute,
} as any)
const LearnRoadmapIdTopicIdRoute = LearnRoadmapIdTopicIdRouteImport.update({
  id: '/$roadmapId_/$topicId',
  path: '/$roadmapId/$topicId',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/habits': typeof HabitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$roadmapId_/$topicId': typeof LearnRoadmapIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/sitemap.xml'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/habits/'
    | '/learn/'
    | '/learn/$roadmapId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/sitemap.xml'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/habits'
    | '/learn'
    | '/learn/$roadmapId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/sitemap.xml'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/habits/'
    | '/learn/'
    | '/learn/$roadmapId_/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HabitsRoute: typeof HabitsRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/habits/': {
      id: '/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/learn/$roadmapId': {
      id: '/learn/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/learn/$roadmapId'
      preLoaderRoute: typeof LearnRoadmapIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/learn/$roadmapId_/$topicId': {
      id: '/learn/$roadmapId_/$topicId'
      path: '/$roadmapId/$topicId'
      fullPath: '/learn/$roadmapId/$topicId'
      preLoaderRoute: typeof LearnRoadmapIdTopicIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface HabitsRouteChildren {
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

interface LearnRouteChildren {
  LearnRoadmapIdRoute: typeof LearnRoadmapIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnRoadmapIdTopicIdRoute: typeof LearnRoadmapIdTopicIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnRoadmapIdRoute: LearnRoadmapIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnRoadmapIdTopicIdRoute: LearnRoadmapIdTopicIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HabitsRoute: HabitsRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
